#! /bin/sh
set -euf -o pipefail

if [ $# -lt 2 ]; then
	echo "Usage: $0 <action>"
	echo "       $0 frag <input-file> <cc> <cflags>..."
	echo "       $0 name <input-file>"
	exit 1
fi

D=$(dirname $0)
action=$1
input=$2
shift 2
base=$(basename "$input")
case "$base" in
	compile-*.c)
		define=${base%%.c}
		define=${define##compile-}
		case "$action" in
			frag)
				"$D"/if_compiles "$input" "#define $define 1" "#define $define 0" "$@"
				;;
			name)
				echo "$define"
				;;
			*)
				>&2 echo "Unrecognized action '$action'"
				exit 1
				;;
		esac
		;;
	*)
		>&2 echo "Unrecognized filename pattern '$base'"
		exit 1
		;;
esac
