#! /bin/sh
set -euf -o pipefail

if [ $# -lt 2 ]; then
	echo "Usage: $0 <input-file> <cc> <cflags>..."
	exit 1
fi

D=$(dirname $0)
input=$1
shift 1
base=$(basename "$input")
case "$base" in
	compile-*.c)
		define=${base%%.c}
		define=${define##compile-}
		"$D"/if_compiles "$input" "#define $define 1" "#define $define 0" "$@"
		;;
	warn-on-failure-*.c)
		warn_msg=$(grep '^/\* WARN:' <"$input" | sed -e 's;/\* WARN: \(.*\) \*/;"\1";')
		"$D"/if_compiles "$input" "/* $base build succesfully, unexpectedly */
#warning $warn_msg" "/* $base build failed (as expected) */" "$@"
		;;
	*)
		>&2 echo "Unrecognized filename pattern '$base'"
		exit 1
		;;
esac
