#!/bin/sh

: ${USE_SYSTEMD=true}
: ${USE_OPENRC=false}
: ${PREFIX:=/usr}
: ${SYSCONFDIR:=/etc}
: ${RUNSTATEDIR:=/var/run}
: ${systemd_unitdir:=${PREFIX}/lib/systemd}
: ${LIBEXEC:=${PREFIX}/libexec}

set -euf

cd "$(dirname "$0")"

install -d "$DESTDIR$PREFIX/bin"
install illum-d "$DESTDIR$PREFIX/bin"

if $USE_SYSTEMD; then
	install -d "$DESTDIR${systemd_unitdir}/system"
	sed -e 's;@bindir@;'$PREFIX'/bin;' \
		"illum.service" > "$DESTDIR${systemd_unitdir}/system/illum.service"
fi

if $USE_OPENRC; then
	install -d "$DESTDIR$SYSCONFDIR/init.d"
	sed -e 's;@bindir@;'$PREFIX'/bin;' \
	    -e 's;@runstatedir@;'$RUNSTATEDIR';' \
	    -e 's;@libexec@;'$LIBEXEC';' \
		"illum.openrc" > "$DESTDIR$SYSCONFDIR/init.d/illum"
	chmod +x "$DESTDIR$SYSCONFDIR/init.d/illum"

	mkdir -p "$DESTDIR$LIBEXEC/illum"
	install with-syslog "$DESTDIR$LIBEXEC/illum"
fi
