#! /bin/sh
set -euf -o pipefail

if [ $# -eq 1 ]; then
	tree_ish="$1"
else
	tree_ish=HEAD
fi

cd "$(dirname $0)"
pv=$(git describe --always "$tree_ish")
ph=$(git rev-parse "$tree_ish")
pn="illum-$ph"
git archive --format tar --prefix="$pn" -o "$pn".tar "$tree_ish"
